# Generated by Django 5.2.6 on 2025-09-17 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('spotify_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(blank=True, max_length=50, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='music.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(blank=True, max_length=50, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('album_name', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('key', models.CharField(blank=True, help_text='Musical key (e.g., C, Am, F#)', max_length=10, null=True)),
                ('tempo_bpm', models.IntegerField(blank=True, help_text='Tempo in beats per minute', null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_songs', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, to='music.genre')),
            ],
            options={
                'ordering': ['title', 'artist__name'],
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
