# Generated by Django 5.2.6 on 2025-09-26 19:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('answer_type', models.CharField(choices=[('STAR', 'STAR'), ('BASIC', 'Basic')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BasicAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Basic Answer',
                'verbose_name_plural': 'Basic Answers',
            },
            bases=('answers.answer',),
        ),
        migrations.CreateModel(
            name='StarAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answer')),
                ('situation', models.TextField()),
                ('task', models.TextField()),
                ('action', models.TextField()),
                ('result', models.TextField()),
            ],
            options={
                'verbose_name': 'STAR Answer',
                'verbose_name_plural': 'STAR Answers',
            },
            bases=('answers.answer',),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='answers_ans_search__457a29_gin'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answer_type'], name='answers_ans_answer__41b2d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'user')},
        ),
    ]
